services:
    redis:
        container_name: redis
        image: 'redis/redis-stack:latest'
        ports:
            - 6379:6379
        volumes:
            - ./db/:/data
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    app:
        container_name: app
        build:
            context: ./
            dockerfile: ./app/Dockerfile
            target: dev
        command: ["pnpm", "run", "dev"]
        ports:
            - '3000:3000'
        volumes:
            - ./app:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        restart: always
        depends_on:
            - redis

    video-search-service:
        container_name: video-search-service
        build:
            context: ./
            dockerfile: ./services/video-search/Dockerfile
            target: dev
        environment:
            - REDIS_URL=redis://redis:6379
        command: ["pnpm", "run", "dev"]
        ports:
            - '8000:8000'
        volumes:
            - ./services/video-search:/usr/src/app
            - /usr/src/app/node_modules
        restart: always
        depends_on:
            - redis